### ISSUE TITLE
大节点的delegate tx 太多，主要考虑鼠标下拉后加载

### ISSUE THREAD

**Issue by liangping** [ping-pub/look#2]
![Screenshot_20191109_070654_com android chrome](https://user-images.githubusercontent.com/2882920/68516893-51593a80-02c0-11ea-97b9-14594406f61b.jpg)

大节点tx数据量太大，一次性加载不完全。考虑更新数据获取方式，但不是用分页显示

**Comment by dingyiming** [comment]
问题是拿一条也拿不出来，很奇怪
