### ISSUE TITLE
License / Usage Check

### ISSUE THREAD

**Issue by chillyvee** [ping-pub/look#30]
Hello, Ping.pub team.

I was learning how your software worked and experimenting with recommending validators.  

I noticed there is no license / usage guideline published for your repository.

Am I free to modify your software and deploy it on my website for others to use?

**Comment by liangping** [comment]
@chillyvee Hello. Be free to use it as you want. But donation are really appreciated.

**Comment by chillyvee** [comment]
Got it.  Thank you so much @liangping !
