### ISSUE TITLE
Validator not visible when jailed

### ISSUE THREAD

**Issue by Creamers158** [ping-pub/look#6]
Like asked, here is the issue on git like be discussed on telegram.
On the Sentinel Explorer it was visible that a validator (DragonStake) was jailed for 8 hours since block 312008.
On ping.pub explorer it was not visible that this validator was jailed on the Inactive tab and the validator even disappeared on the Uptime page list. Also in history before block 312008 the validator was not visible anymore and disappeared completely from the list.
Strangely enough another validator named BigCat is visible Jailed and inactive?!
On telegram ping.pub received some prove by pictures.

**Comment by liangping** [comment]
fixed
